// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6f-CNgOcdXk54ioltQbdiUHptWEW9RVA',
    appId: '1:1066218707269:web:09cc5dba227fd50006c62c',
    messagingSenderId: '1066218707269',
    projectId: 'eshoping-e11e1',
    authDomain: 'eshoping-e11e1.firebaseapp.com',
    storageBucket: 'eshoping-e11e1.appspot.com',
    measurementId: 'G-0BJFFMQBEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrT05TCQsBEi7Vi17CHfUvdOMXbrRqWks',
    appId: '1:1066218707269:android:696d119a5f90b4f606c62c',
    messagingSenderId: '1066218707269',
    projectId: 'eshoping-e11e1',
    storageBucket: 'eshoping-e11e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3xF7YzYU9lP8XGQkTl0PyHhnaD7ObP0',
    appId: '1:1066218707269:ios:247c4cc928f5dc8f06c62c',
    messagingSenderId: '1066218707269',
    projectId: 'eshoping-e11e1',
    storageBucket: 'eshoping-e11e1.appspot.com',
    iosBundleId: 'com.example.eShoping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3xF7YzYU9lP8XGQkTl0PyHhnaD7ObP0',
    appId: '1:1066218707269:ios:e5bee17ed1d6584a06c62c',
    messagingSenderId: '1066218707269',
    projectId: 'eshoping-e11e1',
    storageBucket: 'eshoping-e11e1.appspot.com',
    iosBundleId: 'com.example.eShoping.RunnerTests',
  );
}
